name: Test Resource Group deployment

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: S001DEMOSUB

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check content in runner
        shell: pwsh
        run: |
          (Get-ChildItem -Recurse -Path $GITHUB_WORKSPACE).FullName
          Get-ChildItem env:

      - name: Install Azure PowerShell
        shell: pwsh
        run: |
          Get-Module -ListAvailable

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: 'subscription'
          region: 'westeurope'
          template: 'Modules/Modules/ResourceGroup/deploy.bicep'
          parameters: 'Modules/Parameters/parameters-swatiRG.json'
