name: Kates Resource Group deployment

# Controls when the workflow will run
on: 
  workflow_dispatch: 
  push:
    paths:
      - ".github/workflows/Kate-Deployment.yml"
      - "Parameters/Kate/**"

    
    
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: S001DEMOSUB

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkOutRepository
        uses: actions/checkout@v2
        

      - name: LoginToAzure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: DeployResourceGroup
        uses: Azure/arm-deploy@v1
        with:
          scope: 'subscription'
          region: 'westeurope'
          template: 'Modules/ResourceGroup/deploy.bicep'
          parameters: 'Parameters/Kate/ResourceGroupParametersKate.json'

      - name: DeployStorageAccount
        uses: Azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          ResourceGroupName: 'KatesRG'
          region: 'westeurope'
          template: 'Modules/StorageAccount/deploy.bicep'
          parameters: 'Parameters/Kate/StorageAccountKate.json'
