name: Swatis Resource Group deployment

# Controls when the workflow will run
on: 
  push:
    paths:
      - ".github/workflows/Swati-Deployment.yml"
      - "Parameters/Swati/**"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: SwatiSub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: 'subscription'
          region: 'westeurope'
          template: 'Modules/ResourceGroup/deploy.bicep'
          parameters: 'Parameters/Swati/resourceGroup.parameters.json'

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          region: 'westeurope'
          ResourceGroupName: "SwatisRG"
          template: 'Modules/StorageAccount/deploy.bicep'
          parameters: 'Parameters/Swati/storageAccount.parameters.json'

